PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS years (
    year INTEGER PRIMARY KEY
) STRICT;

CREATE TABLE IF NOT EXISTS days (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    day INTEGER NOT NULL,
    part INTEGER NOT NULL,
    year INTEGER NOT NULL REFERENCES years(year) ON DELETE CASCADE,
    UNIQUE(day, part, year)
) STRICT;

CREATE TABLE IF NOT EXISTS timings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    time_micro_seconds INTEGER NOT NULL,
    day_id INTEGER NOT NULL REFERENCES days(id) ON DELETE CASCADE
) STRICT;