PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS days (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    day INTEGER NOT NULL,
    part INTEGER NOT NULL,
    UNIQUE(day, part)
) STRICT;

CREATE TABLE IF NOT EXISTS timings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    time_ms REAL NOT NULL,
    day_id INTEGER NOT NULL REFERENCES days(id) ON DELETE CASCADE
) STRICT;