#!/bin/bash
echo "Running pre-commit hook"


if [[ -n $(cargo fmt --check) ]]; then
  echo "Failed formatting"
  echo "Please run 'cargo fmt' before committing"
  exit 1
fi


# cargo run 1 -r -y twenty-five -n 0
# git add README.md

echo "Finished running pre-commit hook"